### ISSUE TITLE
畅言评论回推地址怎么填写？

### ISSUE THREAD

**Issue by downdawn** [jhao104/django-blog#21]
畅言评论回推地址怎么填写？评论数据接收不到。。

**Comment by jhao104** [comment]
畅言 ->系统设置 -> 通用设置 -> 评论回推地址 
填`http://你的域名/blog/get_comment/`

**Comment by downdawn** [comment]
谢谢你，去问一下是否有python3的版本？

**Comment by jhao104** [comment]
@downdawn 暂时不支持

**Comment by downdawn** [comment]
本地调试怎么设置白名单才能显示评论？

**Comment by jhao104** [comment]
> 本地调试怎么设置白名单才能显示评论？

什么白名单
