### ISSUE TITLE
3.8 跑不起来。

### ISSUE THREAD

**Issue by marklove5102** [jhao104/django-blog#30]
up主更新下可好？

**Comment by jhao104** [comment]
支持版本 python2.7 Django1.10   Django更新的太快了 最需要指定版本。 兼容不了的话建议用virtualenv或者anaconda

**Comment by E0001** [comment]
请问一下博客有没有前后端分离的版本呢

**Comment by jhao104** [comment]
> 请问一下博客有没有前后端分离的版本呢

没有，也没有打算做，博客的话用js去渲染对seo不好
