### ISSUE TITLE
想把部署到阿里云服务器上,应该怎么做呢?

### ISSUE THREAD

**Issue by Applenice** [jhao104/django-blog#4]
请问我现在想部署在阿里云服务器上,应该怎么做呢,Nginx+uwsgi都安装了,但是有些地方不会配置,自己尝试了一下,但是报502的错误了.很尴尬.

**Comment by jhao104** [comment]
应该是你配置的问题，看下Nginx和uwsgi的错误日志，看看哪里出了问题。 可以参考我这篇博客
http://www.spiderpy.cn/blog/detail/9

**Comment by Applenice** [comment]
好的,我晚上再研究一下,有不明白再请教您,非常感谢.
